version: '3'
services:
  pyspider-redis:
    restart: always
    image: redis
    ports:
    - "6379:6379"

  pyspider-splash:
    image: scrapinghub/splash
    restart: always
    environment:
      PYTHONPATH: /opt/pyspider/projects
    working_dir: /opt/pyspider/projects
    ports:
    - 8050:8050

  pyspider-result:
    image: icy/pyspider
    restart: always
    environment:
      PYTHONPATH: /opt/pyspider/projects
    working_dir: /opt/pyspider/projects
    volumes:
      - ../:/opt/pyspider
    command: -c conf/config.json result-worker --result-cls=libs.result_worker.ResultWorker

  pyspider-phantomjs:
    image: icy/pyspider
    restart: always
    environment:
      PYTHONPATH: /opt/pyspider/projects
    working_dir: /opt/pyspider/projects
    volumes:
      - ../:/opt/pyspider
    command: -c conf/config.json phantomjs

  pyspider-processor:
    image: icy/pyspider
    restart: always
    environment:
      PYTHONPATH: /opt/pyspider/projects
    working_dir: /opt/pyspider/projects
    volumes:
      - ../:/opt/pyspider
    command: -c conf/config.json processor

  pyspider-fetcher:
    image: icy/pyspider
    restart: always
    environment:
      PYTHONPATH: /opt/pyspider/projects
    working_dir: /opt/pyspider/projects
    volumes:
      - ../:/opt/pyspider
    command: -c conf/config.json fetcher

  pyspider-scheduler:
    image: icy/pyspider
    restart: always
    environment:
      PYTHONPATH: /opt/pyspider/projects
    working_dir: /opt/pyspider/projects
    volumes:
      - ../:/opt/pyspider
    command: -c conf/config.json scheduler

  pyspider-web:
    image: icy/pyspider
    restart: always
    environment:
      PYTHONPATH: /opt/pyspider/projects
    working_dir: /opt/pyspider/projects
    volumes:
      - ../:/opt/pyspider
    ports:
    - "5000:5000"
    command: -c conf/config.json webui

  pyspider-mongo:
    image: mongo
    restart: always
    ports:
    - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pyspider
    volumes:
    - ./data/mongo:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
    - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: pyspider
      ME_CONFIG_MONGODB_SERVER: pyspider-mongo
    volumes:
    - ./data/mongo:/data/db